### ISSUE TITLE
"backend_url" unknown..?

### ISSUE THREAD

**Issue by Fritsl** [borisdayma/dalle-mini#163]
I am totally new on Hugging Face and this entire thing, trying to learn..

I wanted to do a "clean clone" of this project, to make sure I was not messing anything up, and so I can dismantle to learn.

I got stuck in not being able to access "backend_url" as apparently it is stored in "st.secrets["BACKEND_SERVER"]" in main.py

Am i being an idiot, is this how you keep people out - or is there a way for me to do a "clean clone" -> copy the project to a place where I can hammer it without disturbing you guys?

Thanks

**Comment by pcuenca** [comment]
Hi Frits!

Unfortunately we can't share the backend urls because of concerns about DDoS, but all the code is being done in the open in this repo. If you want to access the old model, we believe that an inference notebook from a few weeks ago would be your best bet, as it will guide you through the steps involved.

The following link should open a colab notebook that refers to one of the old models, so you can experiment for yourself:
https://colab.research.google.com/github/borisdayma/dalle-mini/blob/af807f728899b4fe6a8efc21d89e8911356130a5/tools/inference/inference_pipeline.ipynb

Please, give it a go, and good luck with your project!
