### ISSUE TITLE
'How Joe Biden won the election' giving wrong/misleading results

### ISSUE THREAD

**Issue by therealbluepandabear** [borisdayma/dalle-mini#246]
Conservatives are proudly displaying how this tool shows images of 'fraud' if you type 'how Joe Biden won', please fix this/adjust the algorithm for this scenario or similar scenarios to instead show something such as a ballot or people voting or the poll numbers showing he won, et cetera:

![image](https://user-images.githubusercontent.com/50536495/173466060-b466d1ca-bd2b-46cf-b7f2-064d7d8a37b9.png)

Regards,
thebluepandabear

**Comment by therealbluepandabear** [comment]
Why the downvote? This is a misleading result. The claims of 'voter fraud' have been fact-checked and are complete bogus. dalle-mini should try and be as accurate as possible and not lead off to misinformation-fuelled lies.

**Comment by selfKaiHarness** [comment]
One reason and one reason only: There's nothing wrong with it. So I don't see the reason to put in censorship garbage into a fun AI tool such as this. Leave it outta this, okay?

**Comment by DanielChaseButterfield** [comment]
I didn't downvote, but I believe that this is outside the scope of this project. 

The project states that "DALL·E mini is an AI model that generates images from any prompt you give!" Nowhere does the project guarantee that the images generated will accurately represent real world events. In contrast, it's supposed to generate a new work of fiction that has never existed before based off of inputs.

The algorithm simply takes inputs and generates outputs based on the keywords that were inputted, typically using images that are associated with those keywords. This doesn't imply that the images accurately represent those keywords. Therefore, the fact that these images show up on due to the input means that images like this are associated with the input words "how joe biden won the election." Nothing more. Just an effect that people tend to post images like that with those keywords.

Most people educated in AI would understand that the outputs aren't meant to be accurate and that this provides no evidence whatsoever to the claims of voter fraud. So although I agree that the majority of evidence suggests that voter fraud did not lead to Joe Biden's election, this tool isn't meant to generate images that represent reality, and these images can't actually serve as evidence against that. For those reasons, it's out of the scope of this project.

**Comment by Joshagos** [comment]
Did you not read the disclaimer that's listed right on the webpage?
![](https://user-images.githubusercontent.com/86931887/173471093-0f2791f4-67fe-47d8-b6db-3719730358ce.jpeg)

**Comment by therealbluepandabear** [comment]
@Joshagos They don't say that they will leave the bias/misinformation stuff in the program, they are saying that they are analyzing it. This issue is important as it shows some places where the model is 'flawed' (not sure if that's the right term).

**Comment by ScienceDrummer** [comment]
Looks alright to me.

**Comment by therealbluepandabear** [comment]
@ScienceDrummer how does it look 'alright'?

**Comment by smith288** [comment]
The AI determined the phrase and connected it to common imagery linked to the term (probably by the right, obviously).  I dont know how you would connect a picture on your phrase outside of the most used imagery when people say "this is how Biden won" or similar.  Do you want it to give generic pictures of people canvassing a neighborhood even though that's not a common result for such a phrase.

Im sure you can have it present all kinds of politically motivated results based on the input you give it.

**Comment by garoto** [comment]
Person unashamedly asking for censorship of a computer algorithm because it doesn't align with his worldview. It's beyond bonkers at this point.

**Comment by therealbluepandabear** [comment]
'Doesn't align with my worldview' -- since when was the outcome of a fair election someone's own 'worldview'?

**Comment by FrostKiwi** [comment]
DALL-E mini and other similar projects in this space have been a prime example of how to handle this. They are very clear with disclaimers on how the results should be interpreted and acknowledge possible shortcomings with the dataset, whilst listing which datasets were used. Role-model behavior from DALL-E mini's Team.

Setting the bar so high as to require moderation of a neural network's output will, will prevent individual researchers or teams with few resources from doing research in this space, lest their neural networks may produce something unintended.

**Comment by therealbluepandabear** [comment]
Hello guys,

I will be closing this issue now as I have come to the conclusion that this will not be addressed.

I have gotten downvoted to oblivion unfortunately, so the community has spoken on this topic -- I don't want to cause any arguments.

Regards,
thebluepandabear

**Comment by smith288** [comment]
I do appreciate where you are coming from as nobody wants their search results or AI to be influenced one way or another so that it will only output either just our worldview or others.  So it's important to research the results while also checking our own personal biases or desired outcomes.

Also, in today's day and age, it's refreshing to see your last comment.  Many folks become extremely hardened in their positions when it comes to this sort of topic so kudos to you.
