### ISSUE TITLE
'Too much traffic, please try again.'

### ISSUE THREAD

**Issue by Kunlun-Zhu** [borisdayma/dalle-mini#262]
Can't really get results from https://huggingface.co/spaces/dalle-mini/dalle-mini,
would you please try solve this issue

**Comment by cdgamedev** [comment]
> Can't really get results from https://huggingface.co/spaces/dalle-mini/dalle-mini, would you please try solve this issue

I would recommend that you run dalle yourself. You can do so via these one of these two videos:
(Ubuntu) https://www.youtube.com/watch?v=eWpzLIa6v9E
(Windows) https://www.youtube.com/watch?v=OqEuEe-xSKk

Due to an influx of people, the service on huggingface isn't the greatest due to the sheer volume of traffic on the site.
